# backend
backend = "glx";
vsync = true;

# fading (this is your animation)
fading = true;
fade-in-step = 0.05;
fade-out-step = 0.05;

# shadows (optional but looks nice with gaps)
shadow = true;
shadow-radius = 10;
shadow-opacity = 0.25;

# disable blur (if you want performance)
blur:
{
  method = "none";
}

# no rounded corners
corner-radius = 0;
