[bar/top]
width = 100%
height = 23
padding = 1
background = #2e2e3e
foreground = #cdd6f4
modules-right = cpu-temp cpu memory pulseaudio wifi battery
modules-left = i3 mpv
modules-center = date
module-margin = 1
font-0 = "JetBrainsMono Nerd Font:size=9;2"
font-1 = "JetBrainsMono Nerd Font:size=18;3"
font-2 = "Font Awesome 5 Brands:size=10"
[module/date]
type = internal/date
interval = 1

date = %A, %d %b | %H:%M
label = %date%
[module/wifi]
type = custom/script
exec = ~/.config/polybar/wifi-status.sh
interval = 5

click-right = ~/.config/rofi/scripts/wifi-menu.sh
label-font = 1
label = %output%
[module/i3]
type = internal/i3

format = <label-state>

label-focused = %name%
label-focused-background = #313244
label-focused-foreground = #cdd6f4
label-focused-padding = 2

label-unfocused = %name%
label-unfocused-foreground = #6c7086
label-unfocused-padding = 2

label-visible = %name%
label-visible-background = #45475a
label-visible-padding = 2

label-urgent = %name%
label-urgent-background = #f38ba8
label-urgent-foreground = #1e1e2e
label-urgent-padding = 2

[module/cpu-temp]
type = custom/script
exec = sensors | grep 'Core 0' | awk '{print $3}'
interval = 5 
label = %output%

[module/battery]
type = custom/script
exec = ~/.config/polybar/battery.sh
interval = 10

label-font = 1

[module/pulseaudio]
type = internal/pulseaudio

; Sink to be used, if it exists (find using `pacmd list-sinks`, name field)
; If not, uses default sink
; sink = alsa_output.pci-0000_12_00.3.analog-stereo

; Use PA_VOLUME_UI_MAX (~153%) if true, or PA_VOLUME_NORM (100%) if false
; Default: true
use-ui-max = true

; Interval for volume increase/decrease (in percent points)
; Default: 5
interval = 10

; Reverses the increment/decrement on scroll event. Set this to true if you are
; using natural scrolling option on your touchpad.
; New in version 3.7.0
; Default: false
reverse-scroll = false

; Right and Middle click
click-right = pavucontrol

; Available tags:
;   <label-volume> (default)
;   <ramp-volume>
;   <bar-volume>
format-volume = <bar-volume> <label-volume>

; Available tags:
;   <label-muted> (default)
;   <ramp-volume>
;   <bar-volume>
;format-muted = <label-muted>

; Available tokens:
;   %percentage% (default)
;   %decibels%
;label-volume = %percentage%%

; Available tokens:
;   %percentage% (default)
;   %decibels%
label-muted = -x-
label-muted-foreground = #ffffff


bar-volume-width = 6
bar-volume-foreground = #A6E3A1
bar-volume-background = #313244
bar-volume-gradient = false
bar-volume-indicator = |
bar-volume-fill = ━
bar-volume-empty = ━

[module/cpu]
type = internal/cpu
interval = 2

format = CPU-<label>
label = %percentage%%
[module/memory]
type = internal/memory
interval = 2

format = RAM-<label>
label = %percentage_used%%

[module/mpv]
type = custom/script
exec = ~/.config/polybar/mpv-status.sh
interval = 5
